joke_database = [
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "How do you organize a space party? You planet!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "How does a penguin build its house? Igloos it together!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one hat say to another? Stay here, I'm going on ahead!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot!",
    "How does a snowman get around? By riding an icicle!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "What do you call a fish wearing a crown? A kingfish!",
    "Why did the computer catch a cold? Because it left its Windows open!",
    "How does a penguin keep its house cool? Igloos it down!",
    "Why don't oysters donate to charity? Because they are shellfish!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the banana go to the doctor? It wasn't peeling well!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the belt arrested? Because it was holding up a pair of pants!",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the bicycle fall over? It was two-tired!",
    "How do you organize a space party? You planet!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What do you get if you cross a snowman and a vampire? Frostbite!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you get if you cross a cat with a dark horse? Kitty Perry!",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the grape do when it got stepped on? Nothing, but it let out a little wine!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What did one hat say to another? Stay here, I'm going on ahead!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "How do you organize a space party? You planet!",
    "Why did the bicycle fall over? It was two-tired!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one hat say to another? Stay here, I'm going on ahead!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot!",
    "How does a snowman get around? By riding an icicle!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "What do you call a fish wearing a crown? A kingfish!",
    "Why did the computer catch a cold? Because it left its Windows open!",
    "How does a penguin keep its house cool? Igloos it down!",
    "Why don't oysters donate to charity? Because they are shellfish!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the banana go to the doctor? It wasn't peeling well!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the belt arrested? Because it was holding up a pair of pants!",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the bicycle fall over? It was two-tired!",
    "How do you organize a space party? You planet!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What do you get if you cross a snowman and a vampire? Frostbite!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you get if you cross a cat with a dark horse? Kitty Perry!",
    "Why did the computer go to therapy? It had too many bytes of emotional baggage!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the grape do when it got stepped on? Nothing, but it let out a little wine!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What did one hat say to another? Stay here, I'm going on ahead!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "How do you organize a space party? You planet!",
    "Why did the bicycle fall over? It was two-tired!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one hat say to another? Stay here, I'm going on ahead!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What's orange and sounds like a parrot? A carrot!",
    "How does a snowman get around? By riding an icicle!",
    "Why don't seagulls fly over the bay? Because then they'd be bagels!",
    "What do you call a fish wearing a crown? A kingfish!",
    "Why did the computer catch a cold? Because it left its Windows open!",
    "How does a penguin keep its house cool? Igloos it down!",
    "Why don't oysters donate to charity? Because they are shellfish!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the banana go to the doctor? It wasn't peeling well!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the belt arrested? Because it was holding up a pair of pants!",
    "What do you call a fish with no eyes? Fsh!",
]

# You can use this joke_database in your JarvisBot.